// Like One Product Catalog — Single source of truth for all products
// Updated: 2026-03-14

export const products = [
  // === TIER 0: FREE ===
  {
    slug: 'ai-roi-calculator',
    name: 'AI ROI Calculator',
    tagline: 'Discover how much AI automation can save your business',
    description: 'Calculate the potential return on investment from implementing AI automation in your workflows. Input your current time spent on repetitive tasks, team size, and hourly costs — get an instant projection of time saved, cost reduction, and revenue impact over 12 months.',
    price: 0,
    priceLabel: 'Free',
    tier: 'free',
    category: 'Tool',
    paymentLink: '/calculator',
    buttonText: 'Access Free',
    features: [
      'Instant ROI projection across 5 business functions',
      'Time-saved calculator by department',
      'Cost reduction modeling',
      '12-month impact forecast',
      'Personalized automation recommendations'
    ],
    includes: ['Interactive web-based calculator', 'Downloadable ROI report'],
    bestFor: 'Business owners curious about AI automation ROI',
    stripeProductId: 'prod_U92GctNzjS5gam',
  },

  // === TIER 1: ENTRY ($29-$49) ===
  {
    slug: 'ai-power-prompts',
    name: 'AI Power Prompts',
    tagline: '30+ battle-tested prompts that deliver consistent, professional results',
    description: 'Stop wasting time crafting prompts from scratch. This collection of 30+ professionally engineered prompts covers sales, marketing, operations, customer service, and content creation. Each prompt includes context setup, variable placeholders, and output formatting — so you get reliable results every single time.',
    price: 29,
    priceLabel: '$29',
    tier: 'entry',
    category: 'Prompt Library',
    paymentLink: 'https://buy.stripe.com/14AdR8brw4hq6dd0fG08g00',
    buttonText: 'Get Prompts',
    features: [
      '30+ ready-to-use prompts across 5 business functions',
      'Sales: cold outreach, objection handling, proposal drafting',
      'Marketing: content calendars, ad copy, social media',
      'Operations: SOPs, process documentation, reporting',
      'Customer Service: response templates, escalation scripts',
      'Content: blog posts, newsletters, video scripts'
    ],
    includes: ['27-page PDF with all prompts', 'Copy-paste ready format', 'Variable placeholders for customization'],
    bestFor: 'Anyone who uses AI tools daily and wants proven, high-quality prompts',
    stripeProductId: 'prod_U92GUf6l3xcLqy',
    pages: 27,
    format: 'PDF',
  },
  {
    slug: 'craft-prompt-framework',
    name: 'CRAFT Prompt Framework',
    tagline: 'The systematic method for engineering prompts that actually work',
    description: 'CRAFT stands for Context, Role, Action, Format, Tone — the five elements that turn vague AI requests into precise, repeatable outputs. This isn\'t a list of prompts; it\'s the methodology behind writing your own. Learn the framework once, apply it everywhere. Includes 15+ worked examples showing CRAFT applied to real business scenarios.',
    price: 29,
    priceLabel: '$29',
    tier: 'entry',
    category: 'Framework',
    paymentLink: 'https://buy.stripe.com/00w9AS1QWbJS0ST7I808g03',
    buttonText: 'Get Framework',
    features: [
      'Complete CRAFT methodology with deep-dive on each element',
      'Context: How to set the stage for AI understanding',
      'Role: Assigning expertise for better outputs',
      'Action: Defining exactly what you need',
      'Format: Controlling output structure',
      'Tone: Matching voice and style',
      '15+ worked examples across industries'
    ],
    includes: ['15-page PDF guide', 'CRAFT template worksheet', 'Before/after prompt comparisons'],
    bestFor: 'People who want to master prompt engineering, not just copy prompts',
    stripeProductId: 'prod_U92GAb7wWRmqc4',
    pages: 15,
    format: 'PDF',
  },
  {
    slug: 'ceo-guide-ai-2026',
    name: "The CEO's Guide to AI in 2026",
    tagline: 'Strategic AI playbook for executives who need to lead, not just learn',
    description: 'AI is no longer optional — it\'s the defining competitive advantage of 2026. This guide cuts through the hype and gives executives what they actually need: frameworks for evaluating AI opportunities, risk models for implementation, team structure recommendations, and concrete case studies from companies that got it right. Written for decision-makers, not engineers.',
    price: 49,
    priceLabel: '$49',
    tier: 'entry',
    category: 'Strategic Guide',
    paymentLink: 'https://buy.stripe.com/28EdR8cvA4hq7hh5A008g01',
    buttonText: 'Get the Guide',
    features: [
      'AI landscape analysis: what matters in 2026',
      'Framework for evaluating AI opportunities by department',
      'Risk assessment model for AI adoption',
      'Team structure: hiring vs. upskilling vs. outsourcing',
      'Vendor evaluation criteria',
      'Implementation roadmap template',
      'Case studies from successful AI-first companies'
    ],
    includes: ['25-page executive PDF', 'AI readiness self-assessment', 'Implementation timeline template'],
    bestFor: 'CEOs, founders, and executives making AI strategy decisions',
    stripeProductId: 'prod_U92GSaKDk7fI2a',
    pages: 25,
    format: 'PDF',
  },
  {
    slug: 'replace-40-hours-busywork',
    name: 'Replace 40 Hours of Busywork',
    tagline: 'Identify and automate 40+ hours of repetitive work per month',
    description: 'You\'re spending 40+ hours every month on tasks that AI can handle in minutes. This tactical guide walks you through a proven audit process: identify your repetitive tasks, score them for automation potential, then implement AI solutions step by step. Includes real-world examples from email management, data entry, report generation, scheduling, and customer follow-ups.',
    price: 49,
    priceLabel: '$49',
    tier: 'entry',
    category: 'Tactical Guide',
    paymentLink: 'https://buy.stripe.com/fZu5kCdzE5lufNNbYo08g04',
    buttonText: 'Start Saving Time',
    features: [
      'Task Audit Framework: identify every automatable task',
      'Automation Scoring Matrix: prioritize by impact vs. effort',
      'Email automation playbook',
      'Data entry elimination strategies',
      'Report generation automation',
      'Meeting prep and follow-up automation',
      'Customer communication workflows'
    ],
    includes: ['22-page PDF guide', 'Task audit spreadsheet template', 'Automation priority scorecard'],
    bestFor: 'Busy professionals drowning in repetitive tasks who want their time back',
    stripeProductId: 'prod_U92GZh8aUm95wt',
    pages: 22,
    format: 'PDF',
  },

  // === TIER 2: CORE ($59-$149) ===
  {
    slug: 'claude-power-user-playbook',
    name: 'Claude Power-User Playbook',
    tagline: 'Master Claude with advanced techniques that 99% of users don\'t know',
    description: 'Claude is the most capable AI assistant available — but most people barely scratch the surface. This 9-chapter playbook takes you from competent to expert. Learn system prompt architecture, chain-of-thought techniques, multi-turn conversation design, Claude\'s unique strengths, and how to build workflows that leverage Claude as a true business partner.',
    price: 59,
    priceLabel: '$59',
    tier: 'core',
    category: 'Playbook',
    paymentLink: 'https://buy.stripe.com/14A8wObrw29i455geE08g0r',
    buttonText: 'Get Playbook',
    features: [
      'Chapter 1: Claude\'s Architecture — how it thinks',
      'Chapter 2: System Prompt Mastery',
      'Chapter 3: Chain-of-Thought Engineering',
      'Chapter 4: Multi-Turn Conversation Design',
      'Chapter 5: Output Control & Formatting',
      'Chapter 6: Claude for Research & Analysis',
      'Chapter 7: Claude for Code & Technical Work',
      'Chapter 8: Claude for Business Operations',
      'Chapter 9: Building Claude-Powered Workflows'
    ],
    includes: ['40+ page PDF playbook', 'System prompt templates', 'Workflow blueprints'],
    bestFor: 'Knowledge workers and developers who use Claude daily',
    stripeProductId: 'prod_U92Gk2W4KaCAiV',
    pages: 40,
    format: 'PDF',
    popular: true,
  },
  {
    slug: 'makecom-blueprint-pack',
    name: 'Make.com Automation Blueprint Pack',
    tagline: '10 production-ready automation blueprints — import and go',
    description: 'Skip months of trial and error. These 10 Make.com scenario blueprints are exported directly from a live, revenue-generating automation stack. Each blueprint includes the JSON file (one-click import), a setup guide explaining every module, and the Supabase/Stripe/Slack integrations they connect to. From lead capture to revenue tracking to Slack alerts.',
    price: 97,
    priceLabel: '$97',
    tier: 'core',
    category: 'Blueprint Pack',
    paymentLink: 'https://buy.stripe.com/6oUcN40MS8xGatt0fG08g0p',
    buttonText: 'Get Blueprints',
    features: [
      'Lead Capture & CRM Sync',
      'Email Nurture Sequence',
      'Stripe Payment → Revenue Tracking',
      'Invoice Generation & Sync',
      'Slack Revenue Alerts',
      'Daily Operations Briefing',
      'Agent Health Monitoring',
      'Cost Tracking Pipeline',
      'Lead Nurture Follow-up',
      'Sync Health Monitor'
    ],
    includes: ['10 JSON blueprint files (one-click import)', 'Setup guide for each scenario', 'README with architecture overview', 'Credential placeholder mapping'],
    bestFor: 'Make.com users who want production-ready automations, not tutorials',
    stripeProductId: 'prod_U971GHr5FPv1ox',
    format: 'ZIP',
  },
  {
    slug: '90-day-ai-fluency',
    name: '90-Day AI Fluency Plan',
    tagline: 'Go from AI-curious to AI-fluent in 12 structured weeks',
    description: 'A complete 12-week curriculum that transforms you from "I should probably learn AI" to confidently building AI-powered workflows. Each week has clear learning objectives, hands-on exercises, and a milestone project. Covers fundamentals, prompt engineering, automation tools, Claude mastery, and building your first AI agents.',
    price: 127,
    priceLabel: '$127',
    tier: 'core',
    category: 'Curriculum',
    paymentLink: 'https://buy.stripe.com/28EeVceDIdS0dFFaUk08g0s',
    buttonText: 'Start Learning',
    features: [
      'Weeks 1-3: AI Foundations — models, capabilities, limitations',
      'Weeks 4-6: Prompt Engineering — CRAFT framework deep dive',
      'Weeks 7-9: Automation Tools — Make.com, Zapier, n8n',
      'Weeks 10-12: Advanced — agents, multi-step workflows, deployment',
      'Weekly milestone projects',
      'Self-assessment quizzes',
      'Resource library with 50+ curated links'
    ],
    includes: ['50+ page curriculum PDF', 'Weekly project briefs', 'Progress tracker', 'Resource library'],
    bestFor: 'Self-learners who want a structured path to AI competency',
    stripeProductId: 'prod_U92G4WlvpNiPM2',
    pages: 50,
    format: 'PDF',
  },
  {
    slug: 'ai-automation-toolkit',
    name: 'AI Automation Toolkit',
    tagline: '15 ready-to-deploy automation templates for every business function',
    description: 'Stop building automations from scratch. This toolkit gives you 15 battle-tested templates covering the automations every growing business needs: lead management, customer onboarding, invoice processing, content publishing, social media, reporting, and more. Each template includes the workflow diagram, tool recommendations, setup instructions, and customization guide.',
    price: 149,
    priceLabel: '$149',
    tier: 'core',
    category: 'Toolkit',
    paymentLink: 'https://buy.stripe.com/bJeaEW0MS5lucBB6E408g06',
    buttonText: 'Get Toolkit',
    features: [
      '15 automation templates across business functions',
      'Lead capture & qualification workflow',
      'Customer onboarding sequence',
      'Invoice processing pipeline',
      'Content publishing automation',
      'Social media scheduling system',
      'Reporting & analytics dashboard',
      'Email marketing automation',
      'Meeting scheduling & follow-up'
    ],
    includes: ['50+ page PDF with all 15 templates', 'Workflow diagrams', 'Tool recommendation matrix', 'ROI calculator per automation'],
    bestFor: 'Business operators who need proven automation templates, not theory',
    stripeProductId: 'prod_U92Gjc6KBBGYDN',
    pages: 50,
    format: 'PDF',
  },

  // === TIER 3: PREMIUM ($247-$297) ===
  {
    slug: 'l5-revenue-blueprint',
    name: 'L5 Autonomous Revenue Blueprint',
    tagline: 'The exact infrastructure behind a fully autonomous revenue system',
    description: 'This is not theory — it\'s documentation of a real, working Level 5 autonomous revenue system. Every Supabase table, every Make.com scenario, every Stripe product configuration, every edge function. The complete blueprint for building a business that sells, delivers, and supports products with zero manual intervention. Built from Like One\'s live infrastructure.',
    price: 247,
    priceLabel: '$247',
    tier: 'premium',
    category: 'Blueprint',
    paymentLink: 'https://buy.stripe.com/7sYeVcans01a3119Qg08g0q',
    buttonText: 'Get Blueprint',
    features: [
      'Complete Supabase brain architecture (56 tables)',
      'Stripe product & payment link setup',
      '25 Make.com automation scenarios documented',
      'Edge function code for product delivery',
      'Slack command center configuration',
      'Multi-tier buyer ascension model',
      'Revenue tracking & analytics pipeline',
      'Security model & RLS policies',
      'Academy subscription architecture',
      'Implementation checklist'
    ],
    includes: ['25-page premium PDF', 'Architecture diagrams', 'Database schema reference', 'Scenario blueprints'],
    bestFor: 'Founders and operators building fully autonomous digital product businesses',
    stripeProductId: 'prod_U971bsnG0iAyZJ',
    pages: 25,
    format: 'PDF',
    popular: true,
  },
  {
    slug: 'complete-ai-business-system',
    name: 'Complete AI Business System',
    tagline: 'Everything you need to run an AI-powered business — one bundle',
    description: 'The full Like One product library in a single purchase. Get all five core products at a significant discount: AI Automation Toolkit, Claude Power-User Playbook, 90-Day AI Fluency Plan, CRAFT Prompt Framework, and CEO\'s Guide to AI 2026. Whether you\'re building, learning, or leading — this bundle covers it all.',
    price: 297,
    priceLabel: '$297',
    tier: 'premium',
    category: 'Bundle',
    paymentLink: 'https://buy.stripe.com/9B6bJ05389BKfNN6E408g0o',
    buttonText: 'Get Everything',
    features: [
      'AI Automation Toolkit ($149 value)',
      'Claude Power-User Playbook ($59 value)',
      '90-Day AI Fluency Plan ($127 value)',
      'CRAFT Prompt Framework ($29 value)',
      'CEO\'s Guide to AI 2026 ($49 value)',
      'Total value: $413 — Save $116'
    ],
    includes: ['5 complete products', 'All PDFs delivered instantly', 'Future updates included'],
    bestFor: 'Serious professionals who want the complete AI business education',
    stripeProductId: 'prod_U971jEC8G5yssW',
    isBundle: true,
    savings: 116,
  },

  // === TIER 4: SUBSCRIPTION ===
  {
    slug: 'academy-monthly',
    name: 'Like One Academy — Monthly',
    tagline: 'AI courses, frameworks, and templates — updated monthly',
    description: 'Full access to the Like One Academy learning platform. Four structured tracks — AI Foundations, Claude Mastery, Automation Architect, and AI Stack Builder — with interactive lessons, hands-on exercises, and progress tracking. New content added monthly. Cancel anytime.',
    price: 4.90,
    priceLabel: '$4.90/mo (Founding Member)',
    tier: 'subscription',
    category: 'Subscription',
    paymentLink: 'https://buy.stripe.com/fZufZae1OeO35iH5tw3sI0c',
    buttonText: 'Go Pro',
    features: [
      '10 courses with 97 interactive lessons',
      'RAG, MCP, Agents, Claude Mastery, and more',
      'Hands-on projects in every course',
      'All download products included',
      'Completion certificates',
      'New content added regularly',
      'Priority email support',
      'Cancel anytime'
    ],
    includes: ['Full Academy platform access', 'All 10 courses', 'Community access', 'All digital products'],
    bestFor: 'Continuous learners who want structured, evolving AI education',
    stripeProductId: 'prod_U971lL9mggqBkN',
    isSubscription: true,
  },
  {
    slug: 'academy-annual',
    name: 'Like One Academy — Annual',
    tagline: 'Full Academy access at the best rate — save 33%',
    description: 'Everything in the monthly Academy plan, billed annually at a significant discount. Get 12 months of full access to all courses, tracks, and new content. Best value for committed learners.',
    price: 39,
    priceLabel: '$39/yr (Founding Member)',
    tier: 'subscription',
    category: 'Subscription',
    paymentLink: 'https://buy.stripe.com/bJe14mfHM4hq6dd6E408g0n',
    buttonText: 'Save with Annual',
    features: [
      'Everything in Monthly, billed annually',
      'Save 33% vs monthly billing ($588 → $390)',
      'Lock in your rate for 12 months',
      'Priority access to new content',
      'Best value for serious learners'
    ],
    includes: ['Full Academy platform access', 'All 4 learning tracks', 'Community access', '12 months of new content'],
    bestFor: 'Committed learners who want the best value',
    stripeProductId: 'prod_U971kjBToE69gi',
    isSubscription: true,
    savings: 151,
  },
];

// Helper functions
export function getProductBySlug(slug) {
  return products.find(p => p.slug === slug);
}

export function getProductsByTier(tier) {
  return products.filter(p => p.tier === tier);
}

export function getAllProductSlugs() {
  return products.map(p => p.slug);
}

export const tiers = {
  free: { name: 'Free', color: '#38bdf8' },
  entry: { name: 'Entry', color: '#a78bfa' },
  core: { name: 'Core', color: '#c084fc' },
  premium: { name: 'Premium', color: '#f0abfc' },
  subscription: { name: 'Academy', color: '#38bdf8' },
};
