// seo-topics.js — Programmatic SEO Topic Engine
// Each topic generates a /learn/[topic]/ landing page targeting keyword clusters.
// Topics aggregate multiple courses, add GEO-optimized content (stats, FAQs, TL;DRs),
// and capture broad search queries that AI engines cite.

export const topics = [
  {
    slug: 'prompt-engineering',
    title: 'Learn Prompt Engineering',
    h1: 'Prompt Engineering: The Complete Guide',
    description: 'Master prompt engineering with hands-on courses. Learn to write prompts that get exactly what you need from ChatGPT, Claude, and other AI models. Free courses available.',
    tldr: 'Prompt engineering is the skill of writing instructions that get AI to produce exactly what you want. It is the single most important AI skill for 2026. Our courses teach you from zero to advanced techniques like chain-of-thought, few-shot learning, and system prompts.',
    keywords: ['prompt engineering', 'prompt engineering course', 'learn prompt engineering', 'ai prompting', 'how to write prompts', 'prompt engineering tutorial', 'chatgpt prompts', 'claude prompts'],
    courses: ['prompt-writing-101', 'advanced-prompt-engineering', 'claude-for-beginners', 'claude-mastery'],
    stats: [
      { label: 'Average salary increase for prompt engineers', value: '47%', source: 'World Economic Forum 2025' },
      { label: 'Professionals using AI prompts daily by 2026', value: '75%', source: 'Gartner' },
      { label: 'Prompt-related job postings growth (YoY)', value: '312%', source: 'LinkedIn Economic Graph' },
    ],
    faq: [
      { q: 'What is prompt engineering?', a: 'Prompt engineering is the practice of crafting instructions (prompts) that guide AI models like ChatGPT and Claude to produce accurate, useful outputs. It includes techniques like chain-of-thought reasoning, few-shot examples, and system prompt design.' },
      { q: 'Do I need coding skills for prompt engineering?', a: 'No. Prompt engineering is primarily about writing clear, structured instructions in natural language. Our beginner courses assume zero technical background.' },
      { q: 'How long does it take to learn prompt engineering?', a: 'You can write effective prompts in a few hours. Mastering advanced techniques like multi-step reasoning and prompt chaining takes 2-4 weeks of practice with our courses.' },
      { q: 'Is prompt engineering a real career?', a: 'Yes. Prompt engineers earn $80K-$200K+ at companies like Anthropic, Google, and OpenAI. The role is expanding as AI adoption grows across every industry.' },
    ],
    relatedTopics: ['ai-agents', 'claude-ai', 'chatgpt'],
  },
  {
    slug: 'ai-agents',
    title: 'Learn AI Agents',
    h1: 'AI Agents: Build Autonomous Systems That Work For You',
    description: 'Learn to build AI agents that act autonomously. From simple chatbots to multi-agent orchestration. Hands-on courses with real projects. Free to start.',
    tldr: 'AI agents are autonomous systems that can plan, reason, and take actions without human intervention. They are the next evolution beyond chatbots. Our courses teach you to build agents from scratch using Claude, tool use, and multi-agent patterns.',
    keywords: ['ai agents', 'build ai agent', 'ai agent course', 'autonomous ai', 'multi-agent systems', 'ai agent tutorial', 'claude agent', 'agentic ai'],
    courses: ['first-ai-agent', 'multi-agent-orchestration', 'claude-mastery', 'ai-systems-design'],
    stats: [
      { label: 'Enterprise AI agent adoption by 2027', value: '85%', source: 'McKinsey Global Institute' },
      { label: 'Tasks AI agents can handle autonomously', value: '60%', source: 'Anthropic Research 2025' },
      { label: 'Cost reduction from AI agent deployment', value: '40-70%', source: 'Deloitte AI Institute' },
    ],
    faq: [
      { q: 'What is an AI agent?', a: 'An AI agent is a software system that uses an AI model (like Claude or GPT) to autonomously plan, reason, and execute tasks. Unlike chatbots that just respond, agents can use tools, access databases, make decisions, and complete multi-step workflows.' },
      { q: 'What can I build with AI agents?', a: 'Anything from automated email responders and research assistants to full business automation systems. Our students build agents that manage social media, process documents, analyze data, and orchestrate multi-step workflows.' },
      { q: 'Do I need to know how to code to build AI agents?', a: 'Basic coding helps but is not required for our beginner course. We teach both no-code agent building (using tools like Make.com) and code-based approaches (Python, JavaScript).' },
      { q: 'What is multi-agent orchestration?', a: 'Multi-agent orchestration coordinates multiple AI agents working together on complex tasks. Think of it as a team of specialized agents — one researches, one writes, one reviews — all coordinating automatically.' },
    ],
    relatedTopics: ['prompt-engineering', 'ai-automation', 'mcp'],
  },
  {
    slug: 'claude-ai',
    title: 'Learn Claude AI',
    h1: 'Claude AI: Master Anthropic\'s Most Capable AI',
    description: 'Learn Claude AI from beginner to expert. Hands-on courses covering Claude for beginners, Claude Code, advanced prompting, and building with the Anthropic API. Free to start.',
    tldr: 'Claude is Anthropic\'s AI assistant, widely considered the most capable AI for reasoning, writing, and coding. Our courses take you from first conversation to building production applications with the Claude API, Claude Code, and Claude\'s unique features like extended thinking.',
    keywords: ['claude ai', 'learn claude', 'claude tutorial', 'anthropic claude', 'claude ai course', 'claude for beginners', 'claude code', 'claude vs chatgpt'],
    courses: ['claude-for-beginners', 'claude-mastery', 'advanced-prompt-engineering', 'ai-foundations'],
    stats: [
      { label: 'Claude context window', value: '200K tokens', source: 'Anthropic' },
      { label: 'Claude Opus benchmark score (MMLU)', value: '96.4%', source: 'Anthropic Model Card' },
      { label: 'Developers using Claude in production', value: '1M+', source: 'Anthropic 2025' },
    ],
    faq: [
      { q: 'What is Claude AI?', a: 'Claude is an AI assistant made by Anthropic. It excels at reasoning, writing, coding, analysis, and following complex instructions. Claude is available through claude.ai, the API, and Claude Code (a CLI tool for developers).' },
      { q: 'Is Claude better than ChatGPT?', a: 'Claude and ChatGPT have different strengths. Claude tends to excel at longer reasoning chains, nuanced writing, and following detailed instructions. ChatGPT has broader tool integrations. Our comparison course covers this in detail.' },
      { q: 'Can I use Claude for free?', a: 'Yes. Claude offers a free tier at claude.ai with usage limits. Our academy courses on Claude are also free to start — no credit card required.' },
      { q: 'What is Claude Code?', a: 'Claude Code is Anthropic\'s command-line tool that lets Claude work directly in your development environment — reading files, writing code, running tests, and managing git. It\'s the most powerful AI coding assistant available.' },
    ],
    relatedTopics: ['prompt-engineering', 'ai-agents', 'ai-coding'],
  },
  {
    slug: 'ai-automation',
    title: 'Learn AI Automation',
    h1: 'AI Automation: Automate Your Work With AI',
    description: 'Learn to automate repetitive tasks with AI. Build workflows with Make.com, Zapier, and custom AI agents. Save 10-40 hours per week. Free courses available.',
    tldr: 'AI automation combines artificial intelligence with workflow tools to eliminate repetitive tasks. Our courses teach you to build automations that handle email, data entry, content creation, reporting, and more — saving 10-40 hours per week.',
    keywords: ['ai automation', 'ai workflow automation', 'automate with ai', 'ai automation course', 'make.com ai', 'ai business automation', 'no code ai automation'],
    courses: ['automation-architect', 'ai-powered-workflows', 'the-automation-lab', 'ai-for-personal-productivity'],
    stats: [
      { label: 'Hours saved per week with AI automation', value: '10-40', source: 'McKinsey 2025' },
      { label: 'Business processes automatable with AI', value: '45%', source: 'World Economic Forum' },
      { label: 'ROI on AI automation projects', value: '250%+', source: 'Deloitte' },
    ],
    faq: [
      { q: 'What is AI automation?', a: 'AI automation uses artificial intelligence to perform tasks that previously required human effort — like writing emails, processing documents, analyzing data, and managing workflows. Unlike traditional automation (if/then rules), AI automation can handle unstructured data and make judgment calls.' },
      { q: 'Do I need to code to automate with AI?', a: 'No. Tools like Make.com and Zapier let you build AI automations visually with drag-and-drop. Our courses cover both no-code and code-based approaches.' },
      { q: 'What tasks can AI automate?', a: 'Email drafting and responses, data entry and processing, content creation and scheduling, meeting notes and summaries, customer support, invoice processing, social media management, and hundreds more.' },
      { q: 'How fast can I build my first automation?', a: 'With our courses, most students build their first working automation in under 2 hours. The Automation Architect course has you building production-ready workflows by lesson 3.' },
    ],
    relatedTopics: ['ai-agents', 'ai-productivity', 'ai-business'],
  },
  {
    slug: 'rag',
    title: 'Learn RAG (Retrieval-Augmented Generation)',
    h1: 'RAG: Build AI Systems With Custom Knowledge',
    description: 'Learn Retrieval-Augmented Generation (RAG) to build AI systems that use your own data. Vector databases, embeddings, and semantic search. Hands-on courses.',
    tldr: 'RAG (Retrieval-Augmented Generation) lets AI models access and reason over your custom data — documents, databases, knowledge bases — instead of relying only on training data. It is the foundation of enterprise AI. Our courses teach you to build RAG systems from scratch.',
    keywords: ['rag', 'retrieval augmented generation', 'rag tutorial', 'rag course', 'vector database', 'embeddings', 'semantic search', 'ai knowledge base', 'rag ai'],
    courses: ['rag-vector-search', 'the-convergence-lab', 'ai-systems-design', 'ai-infrastructure'],
    stats: [
      { label: 'Enterprise AI projects using RAG', value: '73%', source: 'Gartner 2025' },
      { label: 'Accuracy improvement with RAG vs base models', value: '35-60%', source: 'Microsoft Research' },
      { label: 'RAG engineer job postings (2025-2026)', value: '+420%', source: 'Indeed' },
    ],
    faq: [
      { q: 'What is RAG?', a: 'RAG (Retrieval-Augmented Generation) is a technique that gives AI models access to external knowledge. Instead of relying solely on training data, the AI retrieves relevant documents from your data and uses them to generate accurate, grounded responses.' },
      { q: 'Why is RAG important?', a: 'RAG solves AI hallucination by grounding responses in real data. It lets you build AI systems that know about YOUR business — your docs, products, policies — without expensive model fine-tuning.' },
      { q: 'What are vector databases?', a: 'Vector databases store data as mathematical representations (embeddings) that capture meaning. When you search, they find semantically similar content — not just keyword matches. Popular options include Pinecone, Weaviate, and Supabase pgvector.' },
      { q: 'Do I need to know machine learning for RAG?', a: 'No. Our courses teach RAG using pre-built embedding models and vector databases. You need basic coding skills (Python or JavaScript), but no ML expertise.' },
    ],
    relatedTopics: ['ai-agents', 'ai-coding', 'mcp'],
  },
  {
    slug: 'mcp',
    title: 'Learn MCP (Model Context Protocol)',
    h1: 'MCP: Connect AI to Every Tool You Use',
    description: 'Learn MCP (Model Context Protocol) to build AI integrations that connect Claude and other AI models to databases, APIs, and business tools. Free course available.',
    tldr: 'MCP (Model Context Protocol) is an open standard that lets AI models connect to external tools and data sources. Think of it as USB for AI — one protocol that connects any AI to any tool. Our MCP Masterclass teaches you to build custom MCP servers from scratch.',
    keywords: ['mcp', 'model context protocol', 'mcp tutorial', 'mcp course', 'claude mcp', 'mcp server', 'ai integrations', 'ai tools protocol'],
    courses: ['mcp-masterclass', 'ai-stack-builder', 'ai-infrastructure', 'the-convergence-lab'],
    stats: [
      { label: 'MCP servers in the ecosystem', value: '10,000+', source: 'Anthropic MCP Hub' },
      { label: 'Integration time reduction with MCP vs custom APIs', value: '80%', source: 'Anthropic Developer Survey' },
      { label: 'AI tools supporting MCP', value: 'Claude, Cursor, Windsurf, VS Code+', source: 'MCP Specification' },
    ],
    faq: [
      { q: 'What is MCP?', a: 'MCP (Model Context Protocol) is an open standard created by Anthropic that lets AI assistants connect to external data sources and tools. It provides a universal way for AI to read files, query databases, call APIs, and interact with any software.' },
      { q: 'Why should I learn MCP?', a: 'MCP is becoming the standard for AI integrations. Knowing how to build MCP servers means you can connect AI to any tool — CRMs, databases, internal apps — making AI actually useful for real work, not just chat.' },
      { q: 'Is MCP only for Claude?', a: 'No. MCP is an open protocol supported by many AI tools including Claude, Cursor, Windsurf, VS Code with Copilot, and more. Learning MCP means your skills work across the AI ecosystem.' },
      { q: 'How hard is it to build an MCP server?', a: 'A basic MCP server takes 30-60 minutes to build. Our MCP Masterclass takes you from zero to building production-ready servers that connect AI to databases, APIs, and custom business logic.' },
    ],
    relatedTopics: ['ai-agents', 'claude-ai', 'ai-coding'],
  },
  {
    slug: 'ai-for-business',
    title: 'AI for Business',
    h1: 'AI for Business: Cut Costs, Boost Revenue, Stay Ahead',
    description: 'Learn how AI transforms business operations. ROI calculators, vendor evaluation, AI strategy for executives. Practical courses for business owners and leaders.',
    tldr: 'AI is not a future technology — it is reshaping business today. Our courses teach business owners and executives how to identify AI opportunities, evaluate tools, calculate ROI, and lead AI transformation without needing technical skills.',
    keywords: ['ai for business', 'ai business strategy', 'ai for small business', 'ai business course', 'ai roi', 'business ai tools', 'ai transformation'],
    courses: ['ai-for-business', 'ai-for-executives', 'ai-enterprise-strategy', 'ai-for-sales', 'ai-for-marketing'],
    stats: [
      { label: 'Businesses using AI in operations', value: '72%', source: 'McKinsey Global Survey 2025' },
      { label: 'Average ROI on AI investments', value: '250%', source: 'Accenture' },
      { label: 'SMBs planning AI adoption in 2026', value: '64%', source: 'U.S. Chamber of Commerce' },
    ],
    faq: [
      { q: 'How can AI help my business?', a: 'AI can automate customer service, generate marketing content, analyze sales data, process documents, manage inventory, and streamline operations. Most businesses see 10-40% cost reduction in automated areas within 6 months.' },
      { q: 'Is AI too expensive for small businesses?', a: 'No. Many AI tools are free or under $50/month. Our courses specifically teach cost-effective AI strategies for small businesses, including free tools and automation that pay for themselves.' },
      { q: 'Where should I start with AI for my business?', a: 'Start with our AI for Business Owners course. It helps you identify your highest-ROI AI opportunity, evaluate tools, and build your first automation — all in practical, jargon-free language.' },
      { q: 'Do I need a technical team to use AI?', a: 'Not anymore. Modern AI tools are designed for non-technical users. Our courses teach you to implement AI yourself, and our consulting tier provides done-for-you implementation if needed.' },
    ],
    relatedTopics: ['ai-automation', 'ai-productivity', 'ai-marketing'],
  },
  {
    slug: 'ai-productivity',
    title: 'AI for Personal Productivity',
    h1: 'AI Productivity: Reclaim 10+ Hours Every Week',
    description: 'Learn to use AI for personal productivity. Automate email, scheduling, notes, research, and daily tasks. Save 10+ hours per week with free AI courses.',
    tldr: 'The average knowledge worker spends 60% of their time on tasks AI can handle — email, scheduling, note-taking, data entry, research. Our courses teach you to automate your personal workflow and reclaim 10+ hours every week.',
    keywords: ['ai productivity', 'ai for productivity', 'ai productivity tools', 'ai personal assistant', 'automate daily tasks ai', 'ai time management'],
    courses: ['ai-for-personal-productivity', 'ai-powered-workflows', 'automation-architect', 'claude-for-beginners'],
    stats: [
      { label: 'Time saved per week with AI tools', value: '10-15 hours', source: 'Harvard Business Review 2025' },
      { label: 'Knowledge workers using AI daily', value: '68%', source: 'Microsoft Work Trend Index' },
      { label: 'Productivity increase from AI adoption', value: '40%', source: 'Stanford HAI' },
    ],
    faq: [
      { q: 'How can AI make me more productive?', a: 'AI can draft emails in your voice, summarize meetings, organize your calendar, research any topic in minutes, automate data entry, and handle routine tasks — freeing you for creative and strategic work.' },
      { q: 'What AI tools should I use for productivity?', a: 'Start with Claude (reasoning and writing), then add automation tools like Make.com or Zapier. Our courses walk you through the best tool stack for your specific workflow.' },
      { q: 'Is this for non-technical people?', a: 'Absolutely. Our productivity courses require zero coding knowledge. If you can use email and a web browser, you can use AI to transform your workday.' },
    ],
    relatedTopics: ['ai-automation', 'ai-for-business', 'prompt-engineering'],
  },
  {
    slug: 'ai-marketing',
    title: 'AI for Marketing',
    h1: 'AI Marketing: Create Better Content in Less Time',
    description: 'Learn AI marketing — content creation, social media, email campaigns, SEO, and analytics. Hands-on courses for marketers who want to 10x their output.',
    tldr: 'AI is transforming marketing from content creation to analytics. Our courses teach marketers to use AI for writing, social media, email campaigns, SEO optimization, and data analysis — producing 10x more content without sacrificing quality.',
    keywords: ['ai marketing', 'ai for marketing', 'ai content marketing', 'ai marketing course', 'ai social media marketing', 'ai email marketing', 'ai seo'],
    courses: ['ai-for-marketing', 'ai-content-studio', 'content-generation-pipeline', 'ai-for-sales'],
    stats: [
      { label: 'Marketers using AI in their workflow', value: '82%', source: 'HubSpot State of Marketing 2025' },
      { label: 'Content output increase with AI', value: '10x', source: 'Content Marketing Institute' },
      { label: 'Cost per content piece reduction', value: '60-80%', source: 'Jasper AI Research' },
    ],
    faq: [
      { q: 'Can AI write marketing content?', a: 'Yes. AI can draft blog posts, social media content, email campaigns, ad copy, and product descriptions. The key is using it as a creative partner — providing strategy and editing — rather than fully autonomous content generation.' },
      { q: 'Will AI replace marketers?', a: 'No. AI replaces marketing tasks, not marketers. Marketers who use AI will replace marketers who don\'t. Our courses teach you to be the marketer with AI superpowers.' },
      { q: 'What marketing tasks can AI automate?', a: 'Content drafting, social media scheduling, email personalization, SEO keyword research, competitor analysis, A/B test analysis, report generation, and audience segmentation.' },
    ],
    relatedTopics: ['prompt-engineering', 'ai-automation', 'ai-for-business'],
  },
  {
    slug: 'ai-coding',
    title: 'AI for Coding & Development',
    h1: 'AI Coding: Build Software 10x Faster',
    description: 'Learn to code with AI assistance. Claude Code, Cursor, AI pair programming, and building AI-powered applications. From vibe coding to production systems.',
    tldr: 'AI is the biggest productivity leap in software development since the IDE. Claude Code, Cursor, and other AI tools let developers write code 10x faster. Our courses teach you to build real applications — from vibe coding experiments to production AI systems.',
    keywords: ['ai coding', 'ai for developers', 'claude code', 'ai pair programming', 'vibe coding', 'ai software development', 'build with ai'],
    courses: ['vibe-coding', 'ai-stack-builder', 'building-ai-products', 'ai-systems-design', 'ai-infrastructure'],
    stats: [
      { label: 'Developer productivity increase with AI', value: '55%', source: 'GitHub Copilot Research' },
      { label: 'Developers using AI coding tools', value: '92%', source: 'Stack Overflow Survey 2025' },
      { label: 'Code acceptance rate from AI suggestions', value: '30-40%', source: 'Google DeepMind' },
    ],
    faq: [
      { q: 'Can AI write code?', a: 'Yes. AI can write, debug, refactor, and explain code across most programming languages. Tools like Claude Code can work autonomously in your codebase — reading files, writing code, running tests, and committing changes.' },
      { q: 'What is vibe coding?', a: 'Vibe coding is a style of programming where you describe what you want in natural language and AI generates the code. Our Vibe Coding course teaches you to build complete applications this way — no traditional coding required.' },
      { q: 'Should beginners use AI to learn coding?', a: 'Absolutely. AI is the best coding tutor ever created — it explains concepts at your level, catches your mistakes instantly, and helps you build real projects from day one. Our courses are designed around AI-assisted learning.' },
    ],
    relatedTopics: ['claude-ai', 'ai-agents', 'mcp'],
  },
  {
    slug: 'ai-ethics',
    title: 'AI Ethics & Safety',
    h1: 'AI Ethics: Build Responsible AI Systems',
    description: 'Learn AI ethics, safety, and responsible AI practices. Bias detection, privacy, governance frameworks, and building AI systems you can trust.',
    tldr: 'As AI becomes more powerful, building it responsibly becomes critical. Our courses cover bias detection, privacy protection, AI governance, safety testing, and the ethical frameworks that guide responsible AI development.',
    keywords: ['ai ethics', 'ai safety', 'responsible ai', 'ai bias', 'ai governance', 'ai ethics course', 'ethical ai'],
    courses: ['ai-ethics-and-safety', 'ai-enterprise-strategy', 'ai-for-executives'],
    stats: [
      { label: 'Organizations with AI ethics policies', value: '35%', source: 'MIT Sloan 2025' },
      { label: 'AI incidents reported in 2025', value: '3,200+', source: 'AI Incident Database' },
      { label: 'Companies requiring AI ethics training', value: '58%', source: 'Deloitte Global AI Survey' },
    ],
    faq: [
      { q: 'Why does AI ethics matter?', a: 'AI systems make decisions that affect people\'s lives — hiring, lending, healthcare, criminal justice. Without ethical guardrails, AI can amplify existing biases, violate privacy, and cause real harm. Understanding AI ethics is essential for anyone building or deploying AI.' },
      { q: 'What is AI bias?', a: 'AI bias occurs when AI systems produce unfair outcomes — often because training data reflects historical inequities. Our courses teach you to detect, measure, and mitigate bias in AI systems.' },
      { q: 'Is AI safe?', a: 'AI can be built safely with proper guardrails. Our courses cover safety testing, red-teaming, output filtering, and the safety frameworks used by companies like Anthropic and Google DeepMind.' },
    ],
    relatedTopics: ['ai-for-business', 'ai-agents', 'prompt-engineering'],
  },
  {
    slug: 'ai-creative',
    title: 'AI for Creatives',
    h1: 'AI Creative Tools: Amplify Your Artistic Vision',
    description: 'Learn AI tools for creative work — image generation, video creation, music production, writing, and design. Courses for artists, writers, and musicians.',
    tldr: 'AI is not replacing creativity — it is amplifying it. Our courses teach artists, writers, designers, and musicians to use AI as a creative collaborator: generating ideas, creating visuals, producing music, and building entire creative workflows.',
    keywords: ['ai for creatives', 'ai art', 'ai image generation', 'ai video', 'ai music', 'ai writing', 'ai design tools', 'creative ai'],
    courses: ['ai-for-creatives', 'ai-images-and-video', 'ai-voice-audio', 'ai-content-studio'],
    stats: [
      { label: 'Creatives using AI tools regularly', value: '63%', source: 'Adobe Creative Pulse 2025' },
      { label: 'AI-generated images created daily', value: '80M+', source: 'Everypixel Journal' },
      { label: 'Time saved on creative projects with AI', value: '30-50%', source: 'Canva Design Report' },
    ],
    faq: [
      { q: 'Can AI make art?', a: 'AI can generate images, video, music, and text — but the best results come from human-AI collaboration. Our courses teach you to use AI as a creative partner that amplifies your vision, not replaces it.' },
      { q: 'Which AI tools are best for creatives?', a: 'For images: Midjourney, DALL-E, Stable Diffusion. For video: Kling, Runway. For music: Suno, Udio. For writing: Claude, ChatGPT. Our courses cover the best tools for each creative domain.' },
      { q: 'Will AI replace artists?', a: 'No. AI is a tool, like Photoshop or a synthesizer. The artists who learn to use AI will create things that were previously impossible. Our courses are built for creatives, by creatives.' },
    ],
    relatedTopics: ['prompt-engineering', 'ai-marketing', 'ai-productivity'],
  },
  {
    slug: 'ai-data-analysis',
    title: 'AI for Data Analysis',
    h1: 'AI Data Analysis: Turn Raw Data Into Insights',
    description: 'Learn to use AI for data analysis — spreadsheets, visualization, statistical analysis, and automated reporting. No PhD required.',
    tldr: 'AI makes data analysis accessible to everyone. You no longer need a statistics degree to extract insights from data. Our courses teach you to use AI for spreadsheet analysis, data visualization, statistical testing, and automated reporting.',
    keywords: ['ai data analysis', 'ai analytics', 'ai for data', 'ai spreadsheet', 'ai data visualization', 'ai business intelligence'],
    courses: ['ai-for-data-analysis', 'ai-for-business', 'ai-for-executives', 'ai-for-research'],
    stats: [
      { label: 'Data analysis tasks automatable with AI', value: '70%', source: 'Gartner' },
      { label: 'Faster insights with AI-assisted analysis', value: '5-10x', source: 'Harvard Business Review' },
      { label: 'Non-technical users doing AI data analysis', value: '45%', source: 'Tableau Research' },
    ],
    faq: [
      { q: 'Can AI analyze data without coding?', a: 'Yes. Modern AI tools can analyze spreadsheets, create visualizations, run statistical tests, and generate reports — all from natural language instructions. Our courses teach these techniques step by step.' },
      { q: 'What kind of data can AI analyze?', a: 'Spreadsheets, databases, surveys, financial data, customer data, web analytics, scientific data — virtually any structured or semi-structured data.' },
      { q: 'Is AI data analysis reliable?', a: 'AI data analysis is highly reliable for pattern recognition, summarization, and visualization. For critical decisions, we teach you to validate AI outputs and understand statistical significance.' },
    ],
    relatedTopics: ['ai-for-business', 'ai-productivity', 'ai-coding'],
  },
  {
    slug: 'chatgpt',
    title: 'ChatGPT Courses & Alternatives',
    h1: 'ChatGPT: Tutorials, Tips, and Better Alternatives',
    description: 'Learn to use ChatGPT effectively — or discover why Claude might be better for your needs. Comparison courses, prompt engineering, and hands-on tutorials.',
    tldr: 'ChatGPT popularized AI assistants, but it is not the only option. Our courses teach you to get the most out of ChatGPT AND its competitors — with honest comparisons showing where Claude, Gemini, and other models outperform.',
    keywords: ['chatgpt', 'chatgpt tutorial', 'chatgpt course', 'chatgpt vs claude', 'chatgpt alternative', 'learn chatgpt', 'chatgpt tips', 'best ai chatbot'],
    courses: ['claude-for-beginners', 'ai-foundations', 'prompt-writing-101', 'ai-stack-builder'],
    stats: [
      { label: 'Weekly ChatGPT users', value: '300M+', source: 'OpenAI 2025' },
      { label: 'Users who switched to Claude for work', value: '38%', source: 'AI Tool Survey 2025' },
      { label: 'AI models available to compare', value: '100+', source: 'Artificial Analysis' },
    ],
    faq: [
      { q: 'Is Claude better than ChatGPT?', a: 'For many tasks, yes. Claude consistently outperforms ChatGPT on reasoning, writing quality, instruction following, and coding. ChatGPT has broader tool integrations and image generation. Our comparison course gives you an honest breakdown.' },
      { q: 'Should I learn ChatGPT or Claude?', a: 'Learn both — but Claude skills transfer better. Prompt engineering fundamentals work across all AI models. Our courses teach universal techniques and model-specific optimizations.' },
      { q: 'Is ChatGPT free?', a: 'ChatGPT has a free tier with GPT-4o-mini. ChatGPT Plus ($20/mo) gives you GPT-4o and GPT-o1. Claude also has a free tier. Our courses cover the free options for both platforms.' },
    ],
    relatedTopics: ['claude-ai', 'prompt-engineering', 'ai-agents'],
  },
];

export function getAllTopicSlugs() {
  return topics.map(t => t.slug);
}

export function getTopic(slug) {
  return topics.find(t => t.slug === slug) || null;
}
